### PR TITLE
Remove redundant IsMoving checks in SAM

### PR DESCRIPTION
**Pull request by xanunderscore**
The cast time check already does this

### CODE REVIEW

**Comment by Constmar** [comment]
This nerfs the SAM rotation, makes it go afk and not use any other skills while moving to wait to use those skills instead of using other fillers , i don't think it was redundant chief....

**Comment by xanunderscore** [comment]
> This nerfs the SAM rotation, makes it go afk and not use any other skills while moving to wait to use those skills instead of using other fillers , i don't think it was redundant chief....

This is incorrect. SAM only goes "afk" while moving if you have all 3 sen and Meikyo active. This also happens with the currently released version of RS. See https://github.com/Jaksuhn/RotationSolver/blob/main/RotationSolver.Basic/Actions/BaseAction_ActionInfo.cs#L167

**Comment by Constmar** [comment]
my mistake, it does it now too yes, didn't notice it until now, thought it did other skills meanwhile

**Comment by Jaksuhn** [comment]
in testing

**Pull request closed without merging**
