### PR TITLE
Status override check for reprisal

### PR DESCRIPTION
**Pull request by xanunderscore**
can't use `TargetStatus` for this sadly, it only checks for statuses applied by self

### CODE REVIEW

**Comment by Constmar** [comment]
You don't need to add any check, it's already not overriding reprisal, and it even works for alliance raids, you can do some homework and tell us why that already happens ok?

**Comment by xanunderscore** [comment]
> You don't need to add any check, it's already not overriding reprisal, and it even works for alliance raids, you can do some homework and tell us why that already happens ok?

This is incorrect. RS actually has (or had, I guess, before this PR) no means of checking if a target already has Reprisal. It's possible that it could be implemented on a per-rotation basis (and that might be why you haven't noticed it happening) but that's certainly not the case for any of Archi's default tank rotations.

**Comment by Constmar** [comment]
it might not check specifically for reprisal but it doesn't usually override it in normal usage either, for example
image
in savages and ultimates you're supposed to do mitigation manually anyway
and why can't you make it consistent to the mitigations that we already have then...
like this
https://github.com/Jaksuhn/RotationSolver/blob/98706c61d9f2e80a1bfbc4ed44eb7fa76f548383/RotationSolver.Basic/Rotations/CustomRotation_Actions.cs#L163C4-L163C4

**Comment by xanunderscore** [comment]
> it might not check specifically for reprisal but it doesn't usually override it in normal usage either, for example image

The default tank rotations are actually programmed not to use Reprisal during their two minute burst window, which means that the non-RS tank is generally the one using it on the initial raidwide, so the RS tank has it on cooldown for the subsequent raidwide. I don't know why the default rotations do this - it could be to avoid this problem or it could be an attempt to prevent Reprisal from interfering with burst weaving.

> in savages and ultimates you're supposed to do mitigation manually anyway

This is not a good justification not to fix it.

> and why can't you make it consistent to the mitigations that we already have then... like this https://github.com/Jaksuhn/RotationSolver/blob/98706c61d9f2e80a1bfbc4ed44eb7fa76f548383/RotationSolver.Basic/Rotations/CustomRotation_Actions.cs#L163C4-L163C4

Feint, Addle, and Dismantle are single target.

**Comment by Jaksuhn** [comment]
in testing

**Pull request closed without merging**
